#!/usr/bin/env zsh

echo "#!/usr/bin/env zsh"
echo ""

for tap in $(brew tap); do
  echo "brew tap $tap"
done

brew info --json=v1 --installed | jq -r '.[] | select(.installed[0].used_options != []) | . as $in | reduce .installed[0].used_options[] as $item (""; . + " " + $item) | . as $opt | "brew install " + $in.name + $opt'

for formula in $(brew leaves); do
  echo "brew install $formula"
done

if [[ $OSTYPE == *darwin* ]]; then
  for cask in $(brew cask list); do
    echo "brew cask install $cask"
  done
fi
