#!/usr/bin/env zsh

setopt localoptions err_return

if [[ -z "$SSH_CLIENT" ]]; then
  if os::LINUX; then
    if (( $+commands[xclip] )); then
      xclip "$@"
    elif (( $+commands[xsel] )); then
      xsel --clipboard --input
    fi
  elif os::OSX; then
    osx::xclip "$@"
  fi
else
  ssh::xclip --os "${SSH_OS}"  "$@"
fi
