abbrev-alias -g tl='tmux list-sessions'
abbrev-alias -g ta='command tmux attach -d -t'
abbrev-alias -g tl='command tmux list-sessions'
abbrev-alias -g ts='command tmux start-server; command tmux attach'
abbrev-alias -g gcm='git commit -a -m'
