#!/usr/bin/env zsh

brew tap beeftornado/rmtree
brew tap fisherman/tap
brew tap homebrew/aliases
brew tap homebrew/command-not-found
brew tap homebrew/core
brew tap linuxbrew/extra
brew tap linuxbrew/xorg
brew tap martido/brew-graph
brew tap paulhybryant/myformulae
brew install aria2
brew install assh
brew install bash
brew install ccat
brew install cheat
brew install check
brew install cmake
brew install fasd
brew install findutils
brew install fisherman/tap/fisherman
brew install fzf
brew install gcc
brew install git-extras
brew install gnu-getopt
brew install gnu-sed
brew install gnu-tar
brew install gnu-which
brew install go
brew install gpatch
brew install grc
brew install hh
brew install htop
brew install jq
brew install lsof
brew install martido/brew-graph/brew-graph
brew install mdp
brew install moreutils
brew install most
brew install netcat
brew install node
brew install noti
brew install patchelf  --with-static
brew install peco
brew install percol
brew install pkg-config
brew install psgrep
brew install pstree
brew install ranger
brew install renameutils
brew install shc
brew install sshrc
brew install stow
brew install the_silver_searcher
brew install tig
brew install tldr
brew install tmux
brew install urlview
brew install wget
brew install zsh  --with-pcre
