#!/usr/bin/env zsh

brew tap beeftornado/rmtree
brew tap homebrew/command-not-found
brew tap homebrew/core
brew tap jhawthorn/fzy
brew tap linuxbrew/xorg
brew tap paulhybryant/myformulae
brew install python --with-unicode-ucs4
brew install vim --with-override-system-vi --with-client-server --with-lua
brew install assh
brew install bash
brew install berkeley-db@4
brew install brew-gem
brew install cheat
brew install coreutils
brew install docker-completion
brew install dos2unix
brew install fasd
brew install fish
brew install fpp
brew install fzf
brew install gem-guard
brew install git-extras
brew install gnu-sed
brew install gnu-which
brew install graphviz
brew install grc
brew install hh
brew install htop
brew install jhawthorn/fzy/fzy
brew install jq
brew install linuxbrew/xorg/xorg
brew install mawk
brew install mdp
brew install moreutils
brew install most
brew install netcat
brew install node
brew install noti
brew install paulhybryant/myformulae/fsqlf
brew install paulhybryant/myformulae/powerline-fonts
brew install paulhybryant/myformulae/qfc
brew install paulhybryant/myformulae/zunit
brew install paulhybryant/myformulae/zvanilla
brew install peco
brew install percol
brew install progress
brew install psgrep
brew install python
brew install python3
brew install ranger
brew install ruby
brew install sshrc
brew install stdman
brew install stow
brew install the_silver_searcher
brew install tldr
brew install tmux
brew install todo-txt
brew install util-linux
brew install vim
brew install xonsh
brew install zshdb
